### ISSUE TITLE
Race condition / flakyness in E2E tests

### ISSUE THREAD

**Issue by bastjan** [vshn/floaty#84]
## Describe the bug

Tests panic with a `slice bounds out of range [512:0]` from time to time. Check if this is the tests or floaty itself.

```
--- FAIL: TestE2E_Master (0.00s)
panic: runtime error: slice bounds out of range [512:0] [recovered]
	panic: runtime error: slice bounds out of range [5[12](https://github.com/vshn/floaty/actions/runs/8187580972/job/22388362353#step:7:13):0]

goroutine 6 [running]:
testing.tRunner.func1.2({0x702f80, 0xc0000224c8})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:1634 +0x377
panic({0x702f80?, 0xc0000224c8?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/panic.go:770 +0x[13](https://github.com/vshn/floaty/actions/runs/8187580972/job/22388362353#step:7:14)2
bytes.(*Buffer).readSlice(0x7a80c0?, 0x50?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/bytes/buffer.go:440 +0x105
bytes.(*Buffer).ReadString(...)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/bytes/buffer.go:459
github.com/vshn/floaty.expectUpdate(0xc00012a9c0, 0xc00007f9b0, {0x724f53, 0xe}, 0x3)
	/home/runner/work/floaty/floaty/e2e_test.go:130 +0x2fb
github.com/vshn/floaty.TestE2E_Master(0xc00012a9c0)
	/home/runner/work/floaty/floaty/e2e_test.go:34 +0x22e
testing.tRunner(0xc00012a9c0, 0x7546e8)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:[16](https://github.com/vshn/floaty/actions/runs/8187580972/job/22388362353#step:7:17)89 +0xfb
created by testing.(*T).Run in goroutine 1
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:[17](https://github.com/vshn/floaty/actions/runs/8187580972/job/22388362353#step:7:18)42 +0x390
exit status 2
FAIL	github.com/vshn/floaty	0.005s
```

## Expected behavior

Non-flakey tests.

## To Reproduce

Run tests.

## Environment (please complete the following information):

https://github.com/vshn/floaty/actions/runs/8187515308/job/22388153353
https://github.com/vshn/floaty/actions/runs/8187580972/job/22388362353

**Comment by bastjan** [comment]
on closer examination it is only the tests: 
https://github.com/vshn/floaty/blob/c3ff5f9cfafe816fc0bb6e1963d6f2666661d0f6/e2e_test.go#L88-L89

`bytes.Buffer` is not threadsafe.
